# Generated by Django 3.1.6 on 2021-02-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0003_agecategories_bookformats'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название книги')),
                ('picture', models.ImageField(upload_to='uploads/', verbose_name='Фото обложки')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена (BYN)')),
                ('year', models.SmallIntegerField(blank=True, verbose_name='Год издания')),
                ('num_pages', models.SmallIntegerField(blank=True, verbose_name='Количество страниц')),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN')),
                ('weight', models.SmallIntegerField(blank=True, verbose_name='Вес (гр)')),
                ('qty', models.SmallIntegerField(default=0, verbose_name='Наличие (шт)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Доступен к заказу')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карточки')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения карточки')),
                ('age_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.agecategories')),
                ('authors', models.ManyToManyField(to='dictionaries.Authors', verbose_name='Авторы книги')),
                ('book_format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.bookformats')),
                ('genres', models.ManyToManyField(to='dictionaries.Genres', verbose_name='Жанры')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.publishers')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.series')),
            ],
        ),
    ]
