# Generated by Django 3.1.6 on 2021-03-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название книги')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Фото обложки')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Цена (BYN)')),
                ('year', models.SmallIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('num_pages', models.SmallIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Вес (гр)')),
                ('qty', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Наличие (шт)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен к заказу')),
                ('rating', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Рейтинг')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карточки')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения карточки')),
                ('age_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.agecategories')),
                ('authors', models.ManyToManyField(blank=True, to='references.Authors', verbose_name='Авторы книги')),
                ('book_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.bookformats')),
                ('genres', models.ManyToManyField(blank=True, to='references.Genres', verbose_name='Жанры')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.publishers')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.series')),
            ],
        ),
    ]
