# Generated by Django 3.1.6 on 2021-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена (BYN)'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='num_pages',
            field=models.SmallIntegerField(default=0, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='qty',
            field=models.SmallIntegerField(default=0, verbose_name='Наличие (шт)'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='weight',
            field=models.SmallIntegerField(default=0, verbose_name='Вес (гр)'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='year',
            field=models.SmallIntegerField(default=1900, verbose_name='Год издания'),
        ),
    ]
