# Generated by Django 3.1.6 on 2021-03-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.agecategories'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='authors',
            field=models.ManyToManyField(blank=True, to='references.Authors', verbose_name='Авторы книги'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='book_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.bookformats'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Цена (BYN)'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='genres',
            field=models.ManyToManyField(blank=True, to='references.Genres', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступен к заказу'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='num_pages',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Фото обложки'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.publishers'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='qty',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Наличие (шт)'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.series'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='weight',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Вес (гр)'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
