# Generated by Django 3.1.6 on 2021-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_bookcomments_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='ISBN'),
        ),
    ]
