# Generated by Django 3.1.6 on 2021-03-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('mainapp', '0006_auto_20210321_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.series', verbose_name='Серия'),
        ),
    ]
