# Generated by Django 3.1.6 on 2021-02-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20210224_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0+', max_length=80, verbose_name='Возрастная категория')),
            ],
        ),
        migrations.CreateModel(
            name='BookFormats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Формат книги')),
            ],
        ),
    ]
