# Generated by Django 3.1.6 on 2021-03-15 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210315_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuserdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='extuserdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Пользватель'),
        ),
    ]
