# Generated by Django 3.1.6 on 2021-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210315_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuserdata',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Страна'),
        ),
    ]
