# Generated by Django 3.1.6 on 2021-03-17 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0004_auto_20210318_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('customer_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cart.customercart', verbose_name='Корзина товаров')),
                ('phone', models.CharField(blank=True, default='', max_length=80, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, default='Беларусь', max_length=80, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default='', max_length=80, verbose_name='Город')),
                ('post_index', models.CharField(blank=True, default='', max_length=80, verbose_name='Почтовый индекс')),
                ('address1', models.CharField(blank=True, default='', max_length=120, verbose_name='Адрес 1')),
                ('address2', models.CharField(blank=True, default='', max_length=120, verbose_name='Адрес 2')),
                ('comments', models.TextField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatuses', verbose_name='Статус заказа')),
            ],
        ),
    ]
