# Generated by Django 3.1.6 on 2021-03-18 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_ordercomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='comments',
        ),
        migrations.AddField(
            model_name='ordercomments',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='ordercomments',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercomments',
            name='customer_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.customerorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='ordercomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatuses', verbose_name='Статус заказа'),
        ),
    ]
