# Generated by Django 3.1.6 on 2021-03-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customerorder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='additional',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='email',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='E-mail'),
        ),
    ]
