# Generated by Django 3.1.6 on 2021-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210319_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='email',
            field=models.CharField(max_length=80, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='phone',
            field=models.CharField(max_length=80, verbose_name='Телефон'),
        ),
    ]
