# Generated by Django 3.1.6 on 2021-03-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210319_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='orders.orderstatuses', verbose_name='Статус заказа'),
        ),
    ]
