# Generated by Django 3.1.6 on 2021-03-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210320_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomments',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Рейтинг'),
        ),
    ]
