# Generated by Django 3.1.6 on 2021-03-16 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20210316_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_carts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='BooksInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость')),
                ('book_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_cards', to='mainapp.bookcard', verbose_name='Книга')),
                ('customer_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books_in_cart', to='cart.customercart', verbose_name='Корзинка')),
            ],
        ),
    ]
