# Generated by Django 3.1.6 on 2021-03-17 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210316_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksincart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 17, 20, 28, 15, 736992, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booksincart',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='customercart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customercart',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
