# Generated by Django 3.1.6 on 2021-03-17 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_auto_20210317_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksincart',
            name='customer_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books_in_cart', to='cart.customercart', verbose_name='Корзина товаров'),
        ),
        migrations.AlterField(
            model_name='customercart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cutomer_carts', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
