# Generated by Django 3.1.6 on 2021-03-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210318_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksincart',
            name='customer_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_in_cart', to='cart.customercart', verbose_name='Корзина товаров'),
        ),
    ]
